config/routes.rb
Utool::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "registrations" }

  root 'homes#index'

  resources :homes do
    collection do
      get 'index1'
      get 'index2'
      get 'index3'
      get 'index4'
      get 'index5'
      get 'index6'
    end
  end

  resources :users do
    resources :links
  end

  resources :links do
    collection do
      get 'hit_once'
      post 'list_insert'
    end
  end
  resources :categories

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :links,-> { order("position ASC") }
  has_many :categories

  extend OmniauthCallbacks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def is_self?(user)
    user && user == self
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @links = params[:category_id] ? @user.links.where(category_id: params[:category_id]) : @user.links
    @categories = @user.categories.order_by_id
    @category = Category.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% if current_user %>
  <%= tag("div",id: "user", data: {id: current_user.id, name:current_user.name }) %>
<% end %>

<div class="row">
  <div class="span12">
    <div class="row">
      <div class="span2">
        <h4>個人資料</h4>
        <table >
          <tbody>
            <tr>
              <td>
                <span clas="author"> 
                  <strong> 作者: </strong> 
                </span>
                <%= @user.name %> 
              </td>
            </tr>
            <tr>
              <td>
                <span clas="github"> 
                  <strong> Github: </strong> 
                </span>
                <%= render_link_title("連結", @user.github_link) %>
              </td>
            </tr> 
            <tr>
              <td>
                <span clas="blog"> 
                  <strong> Blog: </strong> 
                </span>
                <%= render_link_title("連結", @user.blog_link) %>
              </td>
            </tr>
          </tbody>
        </table>
        <% if @user.is_self?(current_user) %>
        <%= link_to "新增網站", "#{new_link_path}?category_id=#{params[:category_id]}", class: "btn btn-large btn-block"  %>
        <%= link_to "類別管理", categories_path, class: "btn btn-large btn-block"  %>
        <% end %>
      </div>
      <div class="span9">
        <div class="row">
          <div class="span9">
            <%= link_to "全部", user_path(@user), class: "btn btn-link"  %>
            <% @categories.each do |category| %>
            <%= link_to category.name, "#{user_path(@user)}?category_id=#{category.id}", class: "btn btn-link"  %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div id="sortable">
          <% @links.each do |link| %>
          <%= div_for(link, class: "span3") do %>
          <div class="row">
            <div class="span1">
              <%= render partial: "links/link_image_100",  locals: {link: link} %>
              <%= link_to "內容", link_path(link) ,class: "btn btn-mini btn-block" %>
            </div>
            <div class="span2">
              <h5>
                <%= link_to(link.title,{controller: "links", action: "hit_once",id: link.id,url: link.url} ,target: "_blank")  %>
              </h5>
              <p>
                <%= link.direction %>
              </p>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :stylesheets do %>
<%= stylesheet_link_tag "users" %>
<% end %>

<% content_for :javascripts do %>
<%= javascript_include_tag "users" %>
<% end %>