config/routes.rb
Utool::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => "registrations" }

  root 'homes#index'

  resources :homes do
    collection do
      get 'index1'
      get 'index2'
      get 'index3'
      get 'index4'
      get 'index5'
      get 'index6'
    end
  end

  resources :users do
    resources :links
  end

  resources :links do
    collection do
      get 'hit_once'
      post 'list_insert'
    end
  end
  resources :categories

end

app/models/link.rb
class Link < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  
  belongs_to :author, :class_name => "User", :foreign_key => :user_id

  belongs_to :category, :counter_cache => true
  acts_as_list scope: :user_id

  validates :url, presence: true,uniqueness: { scope: :user_id}

  scope :recent, -> {order("created_at DESC")}
  scope :hot, -> {order("hits DESC")}

  after_create :update_info
 
  def update_info
    update_from_embedly
  end
 

  def update_from_embedly
 
    link = self
 
    urls = [url]
    embedly_api = Embedly::API.new(:key => Setting.embedly_key)
    embedly_objs = embedly_api.oembed(:urls => urls)
 
    response_data = embedly_objs[0].marshal_dump
 
    link.title             =  truncate(response_data[:title], length: 255)
    link.link_type         =  truncate(response_data[:type], length: 255)
    link.author_name       =  truncate(response_data[:author_name], length: 255)
    link.author_url        =  truncate(response_data[:author_url], length: 255)
    link.provider_name     =  truncate(response_data[:provider_name], length: 255)
    link.provider_url      =  truncate(response_data[:provider_url], length: 255)
    link.description       =  response_data[:description]
    link.thumbnail_url     =  response_data[:thumbnail_url]
    link.thumbnail_width   =  response_data[:thumbnail_width]
    link.thumbnail_height  =  response_data[:thumbnail_height]
    link.html              =  response_data[:html]
    link.width             =  response_data[:width]
    link.height            =  response_data[:height]
 
    link.save
  end

  def editable_by?(user)
    user && user == author
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    if(params[:category_name])
      categories = Category.where(name: params[:category_name])
      @links = Link.where(category_id: categories).hot
    else
      @links = Link.hot
    end
  end

  def show
    @link = Link.find(params[:id])
    add_hit
  end

  def new
    @link = Link.new(category_id: params[:category_id])

    #預設加入"未分類"
    if current_user.categories.where(name: '未分類').blank?
      @category = current_user.categories.build(name: '未分類')
      @category.save   
    end 

    @categories = current_user.categories

  end

  def edit
    @link = current_user.links.find(params[:id])
    @categories = current_user.categories

  end

  def create
    @link = current_user.links.build(link_params)

    if @link.save
      @link.insert_at(0)
      redirect_to(new_link_path, flash: {info: "新增成功，再來幾個吧！"})
    else
      # FIX
      #render :new, category_id: @link.category_id
      redirect_to(new_link_path, flash: {warning: "未新增成功，請確認是否為有效網址或已有相同網址。"})
    end
  end

  def update
    @link = current_user.links.find(params[:id])
    if @link.update(link_params)
      redirect_to link_path(@link)
    else
      render :edit
    end
  end
  def destroy
    @link = current_user.links.find(params[:id])
    @link.destroy

    redirect_to user_path(current_user)

  end

  def hit_once
    add_hit
    redirect_to params[:url]
  end

  def list_insert
    @link = current_user.links.find(params[:id])

    if @link.not_in_list?
      #重排順序
      current_user.links.each_with_index do |x, index| 
        Link.update_counters(x.id, position: index)
      end 
    end
    
    #將所移動的元素插入指定位置  
    @link.insert_at(1+params[:position].to_i)
    
    respond_to do |format|
      format.json { head :ok }
    end
  end

  private

  def add_hit
    Link.increment_counter(:hits, params[:id])
  end
  def link_params
    params.require(:link).permit(:url,:category_id,:direction,:summary)
  end

end

app/helpers/links_helper.rb
module LinksHelper
  def render_link_title(title, link)
    link.blank? ?  "未設定" : link_to(title, link)
  end

  def render_link_image(link)
    image_tag(link.thumbnail_url ? link.thumbnail_url : 'noimage.jpg' , style: "vertical-align:middle;")
  end

  def notice_message
    flash_messages = []
    flash.each do |type, message|
      type = :success if type == :notice
      text = content_tag(:div, link_to("x", "#", :class => "close", "data-dismiss" => "alert", :onclick => "document.getElementById('close').style.display='none'") + message, :id => "close", :class => "alert fade in alert-#{type}")
      flash_messages << text if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/views/links/_edit_markdown.html.erb
            <div class="row">
              <div class="span8">
                <div class="control-group text optional link_summary">
                  <label class="text optional control-label" for="link_summary">摘要</label>

                  <ul class="nav nav-tabs" id="myTab">
                    <li><a href="#writetab" data-toggle="tab">編輯(使用markdown語法)</a></li>
                    <li><a href="#previewtab" data-toggle="tab">預覽</a></li>
                  </ul>

                  <div class="tab-content">
                    <div class="tab-pane active" id="writetab">
                      <% if @link.summary.blank? %>
                        <textarea id="text-input" oninput="this.editor.update()" rows="8" cols="60" class="input-xxxlarge" type="text"><%= render partial: "markdown_text" %></textarea>
                      <% else %>
                        <textarea id="text-input" oninput="this.editor.update()" rows="14" cols="60" class="input-xxxlarge" type="text"><%= @link.summary %></textarea>
                      <% end %>
                    </div>
                    <div class="tab-pane markdown-bg" id="previewtab">
                      <div id="preview"></div>
                    </div>
                  </div>

                  <script>
                  jQuery(document).ready(function($){
                    $('#myTab a').click(function (e) {
                      e.preventDefault();
                      $(this).tab('show');

                      $("#preview").html(marked($("#text-input").val()));
                    })

                    $( "#submit-button" ).on('click',function() {
                      var form_id = $("form:first").attr("id");
                      $("#link_summary").val($("#text-input").val());
                      $( "#"+form_id ).submit();
                    });
                  });



                  </script>

                </div>
              <input id="submit-button" name="commit" type="submit" value="儲存資料">

              </div>
              <div class="span4">
                <%= render partial: "markdown_tips" %>
                </div>
              </div>

app/views/links/_form.html.erb
    <%= simple_form_for(@link) do |f| %>
    <% if current_page?(controller: 'links', action: 'new') %>
    <%= f.input :url, label: '網址' %>
    <% else %>
    <%= f.input :url, label: '網址', disabled: true %>
    <% end %>
    <%= f.input :category_id, label: '類別',collection: @categories, selected: @link.category_id %>
    <%= f.input :direction, label: "說明  (30個字以內是好主意)", input_html: { maxlength: 30 } %>
    <%= f.input :summary, as: :hidden %>
    <% end %>

app/views/links/_link_image_100.html.erb
<div class="user_link_image">
  <%= render_link_image(link) %>
</div>

app/views/links/_link_preview.html.erb
  <div class="span8 embly_preview">
    <div class="row">
      <div class="span1 offset1">
        <%= render partial: 'links/link_image_100',  locals: {link: @link} %>
      </div>
      <div class="span2">
        <h5>
          <%= link_to(@link.title,@link.url)  %>
        </h5>
        <p>
          <%= @link.direction %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="span6">
        <ul>
          <li>類別:<%= @link.category.name %></li>
          <li>描述:<%= @link.description %></li>
          <li>點擊數:<%= @link.hits %></li>
        </ul>
      </div>
    </div>
  </div>

app/views/links/_markdown_text.html.erb
Markdown
=========

## what is Markdown?
see [Wikipedia](http://en.wikipedia.org/wiki/Markdown)

> Markdown is a lightweight markup language, originally created by John Gruber and Aaron Swartz allowing people "to write using an easy-to-read, easy-to-write plain text format, then convert it to structurally valid XHTML (or HTML)".

----
## markdown quick reference
# headers

*emphasis*

**strong**

* list

>block quote

    code (4 spaces indent)
[links](http://wikipedia.org)

----
## thanks
* [markdown-js](https://github.com/evilstreak/markdown-js)

app/views/links/_markdown_tips.html.erb
<h4>markdown語法摘要</h4>
<pre><code>標題
  ============ (or----------)</code></pre>
  <pre><code>＃,##,###,####,#####,######小標題</code></pre>
  <pre><code>[連結UTOOL](http://utool.herokuapp.com)</code></pre>
  <pre><code>![ruby icon](http://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Ruby_logo.png/105px-Ruby_logo.png)</code></pre>
  <pre><code>>在這個符號(>)後所寫的字都是區塊，直到整行的最大長度才會換行，如要恢復正常文字請空一行</code></pre>
  <pre><code>```
程式區塊
程式區塊第二行
```</code></pre>
  <p>其他更多用法 請參考 <a href="https://www.google.com.tw/search?safe=off&espv=210&es_sm=91&q=markdown+語法&oq=markdown+語法" target="_blank">markdown語法</a></p>

app/views/links/edit.html.erb
<div class="row">
  <div class="span12">
    <h2>修改</h2>
  </div>
</div>
<div class="row">
  <div class="span4">
    <%= render partial:"form" %>
  </div>

  <%= render partial: 'links/link_preview',  locals: {link: @link} %>


</div>    

<%= render partial: 'edit_markdown',locals: {link: @link} %>

<% content_for :stylesheets do %>
<%= stylesheet_link_tag "links" %>
<% end %>
<% content_for :javascripts do %>
<% end %>

app/views/links/index.html.erb
<div class="row">
  <div class="span1">
  </div>
  <div class="span8">
    <%= link_to "全部", links_path, class: "btn btn-link"  %>
    <%= link_to "討論", "#{links_path}?category_name=討論", class: "btn btn-link"  %>
    <%= link_to "文摘", "#{links_path}?category_name=文摘", class: "btn btn-link"  %>
    <%= link_to "Gem", "#{links_path}?category_name=Gem", class: "btn btn-link"  %>
    <%= link_to "前端技術", "#{links_path}?category_name=前端技術", class: "btn btn-link"  %>
    <%= link_to "教學", "#{links_path}?category_name=教學", class: "btn btn-link"  %>
  </div>
  <div class="span3">
  </div>
</div>

<div class="row">
  <div class="span12">
   <table class="table table-striped table-hover" style="table-layout: fixed;">
    <thead>
     <tr>
       <th style="width:10%"></th>
       <th style="width:10%">類別</th>
       <th style="width:20%">標題</th>
       <th style="width:5%"></th>
       <th style="width:30%">描述</th>
       <th style="width:20%">分享者</th>
       <th style="width:5%">點擊數</th>
     </tr>
   </thead>
   <tbody id="content">
    <% @links.each do |link| %>
    <%= content_tag_for(:tr,link) do %>
    <th>        
      <%= render_link_image(link) %>
    </th>
    <th> 
      <%= link.category.name %>
    </th>
    <th>
      <%= link_to(link.title,{controller: "links", action: "hit_once",id: link.id,url: link.url} ,target: "_blank")  %>
    </th>
    <th>
      <%= link_to "內容",link_path(link),class: "btn btn-mini"  %>
    </th>
    <th>
      <%= truncate(link.description,length: 200) %>
    </th>
    <th>
      <%= gravatar_image_tag(link.author.email.gsub("spam", "mdeering"), :alt => link.author.name,:gravatar => {:size =>15})  %>
      <%= link_to link.author.name, user_path(link.author) %>
    </th>
    <th>
      <%= link.hits %>
    </th>
    <% end %>
    <% end %>

  </tbody>
</table>
</div>
</div>

<% content_for :javascripts do %>
  <%= javascript_include_tag 'links' %>
<% end %>

app/views/links/new.html.erb
<div class="row">
  <div class="span12">
    <h2>新增網址</h2>
    <h6>1.將常用的工具網址複製並貼上</h6>
    <h6>2.選擇類別(稍後可做修改)</h6>
    <h6>3.填入自已備忘的說明文字</h6>
  </div>
</div>
<div class="row">
  <div class="span4">
    <%= render partial:"form" %>
    <input id="submit-button" name="commit" type="submit" value="儲存資料">
  </div>

  <div class="span8 embly_preview">
    <div class="row">
      <div class="selector-wrapper"></div>
<!--        <div class="span1"> 
        <img alt="Logo 50" src="http://www.colorzilla.com/firefox/images/logo-50.png" class="center-block" style="width:75px;height:75;" />
      </div>
      <div class="span2">
        <h5><a href="http://www.colorzilla.com/gradient-editor/">Ultimate CSS Gradient Generator</a></h5>
        <p>
          A powerful Photoshop-like CSS gradient editor from ColorZilla. News: version 4 
        </p>
      </div>  -->
    </div>
  </div>

</div>

<% content_for :stylesheets do %>
<link rel="stylesheet" href="http://cdn.embed.ly/jquery.preview-0.3.2.css" />
<% end %>
<% content_for :javascripts do %>
<script src="http://cdn.embed.ly/jquery.embedly-3.0.5.min.js" type="text/javascript"></script>
<script src="http://cdn.embed.ly/jquery.preview-0.3.2.min.js" type="text/javascript"></script>
<script src="http://embedly.github.io/jquery-preview/lib/mustache.js" type="text/javascript"></script>
<script src="http://embedly.github.io/jquery-preview/lib/underscore.js" type="text/javascript"></script>
<%= javascript_include_tag "links/new" %>
<script>
jQuery(document).ready(function($){
  $( "#submit-button" ).on('click',function() {
    var form_id = $("form:first").attr("id");
    $("#link_summary").val($("#text-input").val());
    $( "#"+form_id ).submit();
  });
});
</script>
<% end %>

app/views/links/show.html.erb
<div class="row">
  <div class="span3">
    <% if @link.editable_by?(current_user) %>
    <div class="row">
      <div class="span1 offset2">
        <%= link_to '修改', edit_link_path(@link) ,class: 'btn btn-block' %>
        <%= link_to '刪除', link_path(@link),class: 'btn btn-block',method: 'delete' ,confirm: 'Are you sure?'  %>
      </div>
    </div>
    <% end %>
  </div>
  <%= render partial: 'links/link_preview',  locals: {link: @link} %>
</div>

<hr></hr>
<div class="row">
  <div class="span10 offset1 markdown-bg">
    <div class="row">
      <div class="span8 offset1">
        <textarea id="originText" style="display:none"><%= @link.summary %></textarea>
        <div id="markdownText"></div>
      </div>
    </div>
  </div>
</div>
</div>

<script>
jQuery(document).ready(function($){

  $("#markdownText").html(marked($("#originText").val()));
});
</script>

<% content_for :stylesheets do %>
<%= stylesheet_link_tag "links" %>
<% end %>